MSTest sample Selenium 4
browserstack/MSTest-browserstack pull request #1
Opened 2024-03-04 09:32 UTC by Baaryan

2024-03-22 13:16 UTC, kamal-kaur04 requested changes
Similar comments as selenium-3

2024-03-22 13:39 UTC, Baaryan commented
Done

2024-03-22 13:39 UTC, Baaryan commented
Done

2024-03-22 13:54 UTC, kamal-kaur04 requested changes

2024-03-22 13:54 UTC, kamal-kaur04 commented on MSTest-browserstack/mac.conf.json
> +    "browserstack.source": "mstest:sample-main:v1.0"
`source` will be the capability

2024-03-22 13:58 UTC, kamal-kaur04 approved these changes

2024-03-26 14:39 UTC, pranavj1001 approved these changes

2024-03-27 05:50 UTC, merged