MSTest sample SDK
browserstack/MSTest-browserstack pull request #4
Opened 2024-03-06 12:57 UTC by Baaryan

2024-03-15 06:23 UTC, kamal-kaur04 requested changes
Please GitHub Actions Workflow like this - https://github.com/browserstack/xunit-browserstack/blob/main/.github/workflows/reviewing_changes.yml

2024-03-15 07:25 UTC, Baaryan commented
Added the GitHub Actions Workflow

2024-03-22 13:09 UTC, kamal-kaur04 requested changes

2024-03-22 13:09 UTC, kamal-kaur04 commented on .gitignore
> +.localhistory/
new line

2024-03-22 13:09 UTC, kamal-kaur04 commented on .github/workflows/reviewing_changes.yml
> +            }
new line

2024-03-22 13:09 UTC, kamal-kaur04 commented on MSTest_browserstack/SampleTest.cs
> +}
new line

2024-03-22 13:09 UTC, kamal-kaur04 commented on MSTest_browserstack/browserstack.yml
> +# Available options are `disable`, `errors`, `warnings`, `info`, `verbose` (Default: errors)
new line

2024-03-22 13:55 UTC, kamal-kaur04 approved these changes

2024-03-22 13:59 UTC, kamal-kaur04 requested changes

2024-03-22 13:59 UTC, kamal-kaur04 commented on .github/workflows/reviewing_changes.yml
> +
new line

2024-03-26 14:39 UTC, pranavj1001 approved these changes

2024-03-27 05:49 UTC, merged